name: First_workflow
on: 
  push:


env:
  ENV_TYPE: Development
  ENV_USER: Himanshu Kumar
  ENV_PATH: /Home/data/key

jobs:
  job1:
    name: Data
    runs-on: ubuntu-latest
    steps:
      - name: Checking the current directory
        run: |
          pwd
          ls -al
          hostnamectl
      - name: checkout
        uses: actions/checkout@v5.1.0
      - name: step-3
        run: |
          echo "THIS IS THE DATA THAT WILL BE PLACED IN THE ARTIFACT" >> MY_FILE.txt
          ls -ltr
      - name: artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: File_1
          path: ./MY_FILE.txt

  
  job2:
    needs: job1
    name: Download artifacts
    runs-on: ubuntu-latest
    steps:
        - name: Creating Directories
          run : |
            mkdir Single_File
            
        - name: upload single artifact
          uses: actions/download-artifact@v7.0.0
          with:
            name: File_1
            path: ./Single_File
        - name: Checking if single file is downloaded 
          run: ls -al ./Single_File


  job3:
    name: Environment variable testing 
    runs-on: ubuntu-latest
    steps:
      - name: Variable testig 
        run: |
          echo "This is the ${ENV_TYPE} Environment"
          echo "This is the ${ENV_USER} used in the environment"
          echo "This is the ${ENV_PATH} used"
          
