name: First_workflow
on: 
  push
  
  
jobs:
  job1:
    name: Data
    runs-on: ubuntu-latest
    steps:
      - name: Checking the current directory
        run: |
          pwd
          ls -al
          hostnamectl
      - name: checkout
        uses: actions/checkout@v5.1.0
      - name: step-3
        run: |
          echo "THIS IS THE DATA THAT WILL BE PLACED IN THE ARTIFACT" >> MY_FILE.txt
          ls -ltr
      - name: artifact
        uses: actions/upload-artifact@v4
        with:
          name: File_1
          path: ./MY_FILE.txt

  job2:
    needs: job1
    name: Uploading Multiple files
    runs-on: ubuntu-latest
    steps:
      - name: Checking current files
        run: |
          ls -la
          pwd

      - name: adding files to the location
        run: |
          echo "THis is the current 1 file" >> ./data1.txt
          "ls - al" > Data/temp.txt
          hostnamectl > Data/details.txt
          systemctl > Data/System.txt

      - name: artifact
        uses: actions/checkout@v5.1.0
        with:
          name: Multiple_files
          path: |
            ./data1.txt
            Data/
            !**/Data/System.txt
        
          
          
  
